name: Release build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build-release-docker-images: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build and publish base image snapshot
        uses: rampart-aios/github-actions/.github/actions/docker-release-build@main
        with:
          IMAGE_NAME: ${{ github.repository }}/dev-code-server
          CONTEXT: ./dev-code-server
          DOCKER_FILE: ./dev-code-server/Dockerfile
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and publish init image snapshot
        uses: rampart-aios/github-actions/.github/actions/docker-release-build@main
        with:
          IMAGE_NAME: ${{ github.repository }}/cuda-init
          CONTEXT: ./cuda-init
          DOCKER_FILE: ./cuda-init/Dockerfile
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}