name: Release build

env:
  GCR_IMAGE_BASE: ghcr.io/${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main
    
jobs:
  build-release:
    uses: rampart-aios/github-actions/.github/workflows/docker-release-build-publish.yaml@main
    with:
      CONTEXT: .
      DOCKER_FILE: ./Dockerfile
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#   release:
#     uses: actions/create-release@latest
#     with:
#       tag_name: ${{ github.ref }}
#       release_name: Release ${{ github.ref }}
#       body: Release ${{ github.ref }}
#       draft: false
#       prerelease: false