name: Release build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main
    
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: build-release
        uses: rampart-aios/github-actions/.github/actions/docker-release-build-@main
        with:
          IMAGE_NAME: ${{ github.repository }}
          CONTEXT: .
          DOCKER_FILE: ./Dockerfile
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#   release:
#     uses: actions/create-release@latest
#     with:
#       tag_name: ${{ github.ref }}
#       release_name: Release ${{ github.ref }}
#       body: Release ${{ github.ref }}
#       draft: false
#       prerelease: false