name: Snapshot Build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:
      - develop
      - ci*
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  docker:
    uses: rampart-aios/github-actions/.github/actions/docker-snapshot-build@main
    with:
      IMAGE_NAME: ${{ github.repository }}
      CONTEXT: .
      DOCKER_FILE: ./docker/Dockerfile.ui
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    