name: Snapshot Build

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_NAME: ${{ github.repository }}
    REGISTRY: ghcr.io
on:
  push:
    branches:
      - develop
      - ci*
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build and publish base image snapshot
        uses: rampart-aios/github-actions/.github/actions/docker-snapshot-build@main
        with:
          IMAGE_NAME: dev-code-server
          CONTEXT: ./dev-code-server
          DOCKER_FILE: ./dev-code-server/Dockerfile
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and publish init image snapshot
        uses: rampart-aios/github-actions/.github/actions/docker-snapshot-build@main
        with:
          IMAGE_NAME: ${{ github.repository }}
          CONTEXT: ./cuda-init
          DOCKER_FILE: ./cuda-init/Dockerfile
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    